### ISSUE TITLE
A question

### ISSUE THREAD

**Issue by cramerx** [sacbnc/FXCommunityOutlook#1]
How did you get "interest" from outlook data? thanks

(I'm not  a programmer...)

**Comment by sacbnc** [comment]
All the data is just embedded in the HTML as tooltips

If you view the page source you will be able to do a find and locate it

**Comment by cramerx** [comment]
I saw later that you did't use myfxbook API...
I'm searching in page source but not found, I don't know how to search...

I'll try to use your program to write a file and then read file in MT4

**Comment by sacbnc** [comment]
Yeah I just pulled straight from the site

Let me know if you run into any problems

**Comment by cramerx** [comment]
I'm really unable to find "interest section" in page source

**Comment by sacbnc** [comment]
By interest do you mean the Percentage field on the tooltip that appears when you hover over a row?

**Comment by cramerx** [comment]
Perc of traders are currently trading X

**Comment by sacbnc** [comment]
Right click > View page source > scroll to line 1440

Should show you the interest for EURUSD to give an example

**Comment by cramerx** [comment]
Ok, found!
and then how does it work?  Search for "div" tag?
Thanks

**Comment by cramerx** [comment]
I had also a request..
Can you add "average long price" and "average short price"?
I would do it but do not know anything about python
Thanks

**Comment by sacbnc** [comment]
I've added average long and short price now

Let me know how you get on with it

**Comment by cramerx** [comment]
Thanks, I'll try something this weekend

**Comment by cramerx** [comment]
Hi, I'd done a little mod. Try to select by "interest" but I unable to remove "%" symbol from "interest" for making a comparison:

`import sys
import lxml.html
import requests

min_interest = 4

def scrape(min_lots):
    url = 'http://www.myfxbook.com/community/outlook'
    doc = requests.get(url)#, proxies=proxies)
    root = lxml.html.fromstring(doc.text)
    
    # get list of all input ids
    all_id_inputs = root.xpath("//input[starts-with(@id,'outlookTip')]/@id")
    
    for id in all_id_inputs:
        # populate string with current id
        xpath_value = '//*[@id="{}"]/@value'.format(id)
        table_value = root.xpath(xpath_value)
        root_table  = lxml.html.fromstring(table_value[0])
    
        # reference 0th of element of all derived xpath variables
        # as a single element list is returned
        symbol = root_table.xpath("//table/tr[1]/td[1]/text()")[0]
    
        short_value =  root_table.xpath("//table/tr[2]/td[2]/text()")[0]
        short_volume = root_table.xpath("//table/tr[2]/td[3]/text()")[0].split(' ')[0]
    
        long_value =  root_table.xpath("//table/tr[3]/td[2]/text()")[0]
        long_volume = root_table.xpath("//table/tr[3]/td[3]/text()")[0].split(' ')[0]

        interest = root_table.xpath("//div/text()")[1].split(' ')[0]
    
        if float(interest) < min_interest: continue  

    
        print interest +  ", " + symbol + ", " + short_value + ", " + short_volume + ", " + long_value + ", " + long_volume

if len(sys.argv) == 1:
    scrape(min_interest)
elif len(sys.argv) == 2:
    scrape(int(sys.argv[1]))`

**Comment by cramerx** [comment]
(I don't know why something inside code tag and sonething outside...)

**Comment by cramerx** [comment]
It would be great if it also would creates a .csv file with:

-date
-interest1, symbol1, short_value1, long_value1
-interest2, symbol2, short_value2, long_value2
-interest3, symbol3, short_value3, long_value3
...
...

**Comment by cramerx** [comment]
Ok, I understand that:

`interes_n=interest.split("%")[0]`

**Comment by cramerx** [comment]
Ok, now works...

`import sys
import lxml.html
import requests

min_interest = 4

def scrape(min_interest):
    url = 'http://www.myfxbook.com/community/outlook'
    doc = requests.get(url)#, proxies=proxies)
    root = lxml.html.fromstring(doc.text)
    
    # get list of all input ids
    all_id_inputs = root.xpath("//input[starts-with(@id,'outlookTip')]/@id")
    
    for id in all_id_inputs:
        # populate string with current id
        xpath_value = '//*[@id="{}"]/@value'.format(id)
        table_value = root.xpath(xpath_value)
        root_table  = lxml.html.fromstring(table_value[0])
    
        # reference 0th of element of all derived xpath variables
        # as a single element list is returned
        symbol = root_table.xpath("//table/tr[1]/td[1]/text()")[0]
    
        short_value =  root_table.xpath("//table/tr[2]/td[2]/text()")[0]
        short_volume = root_table.xpath("//table/tr[2]/td[3]/text()")[0].split(' ')[0]
    
        long_value =  root_table.xpath("//table/tr[3]/td[2]/text()")[0]
        long_volume = root_table.xpath("//table/tr[3]/td[3]/text()")[0].split(' ')[0]

        interest = root_table.xpath("//div/text()")[1].split(' ')[0]
        interest_n = interest.split("%")[0]
    
        if int(interest_n) < min_interest: continue  

    
        print interest +  ", " + symbol + ", " + short_value + ", " + short_volume + ", " + long_value + ", " + long_volume
  

if len(sys.argv) == 1:
    scrape(min_interest)
elif len(sys.argv) == 2:
    scrape(int(sys.argv[1]))

    out_file.close()`

**Comment by cramerx** [comment]
Hi, I edited the code for selecting by "interest" and writing data into a .csv and work well, can I fork?

`# Name   : fx_commoutlook_scraper.py

# Author : Steve Armstrong  (github.com/sacbnc)

# Date   : Sep 2016

# Columns: symbol, short_value, short_volume, long_value, long_volume,

# average_short, average_long, interest

import sys
import lxml.html
import requests
from BeautifulSoup import BeautifulSoup

min_interest = 4

def scrape(min_interest):
    url = 'http://www.myfxbook.com/community/outlook'
    doc = requests.get(url)#, proxies=proxies)
    soup = BeautifulSoup(doc.text)
    root = lxml.html.fromstring(doc.text)

```
# get list of all input ids
all_id_inputs = root.xpath("//input[starts-with(@id,'outlookTip')]/@id")

output = open('list.csv','w')
output.write('date\n')
output.close()


for id in all_id_inputs:
    # populate string with current id
    xpath_value = '//*[@id="{}"]/@value'.format(id)
    table_value = root.xpath(xpath_value)
    root_table  = lxml.html.fromstring(table_value[0])

    # reference 0th of element of all derived xpath variables
    # as a single element list is returned
    symbol = root_table.xpath("//table/tr[1]/td[1]/text()")[0]

    short_value =  root_table.xpath("//table/tr[2]/td[2]/text()")[0]
    short_volume = root_table.xpath("//table/tr[2]/td[3]/text()")[0].split(' ')[0]

    long_value =  root_table.xpath("//table/tr[3]/td[2]/text()")[0]
    long_volume = root_table.xpath("//table/tr[3]/td[3]/text()")[0].split(' ')[0]

    interest = root_table.xpath("//div/text()")[1].split(' ')[0]
    average_short = soup.find(id="shortPriceCell" + symbol).string
    average_long = soup.find(id="longPriceCell" + symbol).string

    interest_n = interest.split("%")[0]

    if int(interest_n) < min_interest: continue

    L = interest + ',' + symbol + ',' + average_short + ',' + average_long + '\n'

    output = open('list.csv','r+')
    output.writelines(L)
    output.close()

    print symbol       + "," + short_value   + "," + \
    short_volume + "," + long_value    + "," + \
        long_volume  + "," + average_short + "," + \
        average_long + "," + interest
```

if len(sys.argv) == 1:
    scrape(min_interest)
elif len(sys.argv) == 2:
    scrape(int(sys.argv[1]))

`

**Comment by cramerx** [comment]
Error:


Traceback (most recent call last):
  File "C:\Users\Marco\Desktop\fx_commoutlook_scraper_MODDED.py", line 4, in <module>
    from BeautifulSoup import BeautifulSoup
ImportError: No module named BeautifulSoup

**Comment by cramerx** [comment]
Then, I want to do some check for server unrespond and so on..
and check for error on writing file.
This .csv fil  will be readed by an MT4 EA

**Comment by sacbnc** [comment]
Glad it's helping you out. Feel free to fork.

By the way change the following to remove the % from interest and avoid adding another line:

`interest = root_table.xpath("//div/text()")[1].split(' ')[0]`

to

`interest = root_table.xpath("//div/text()")[1].split('%')[0]`
